config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'history/index' => 'pages#history'
  get 'modal' => 'pages#modal'
  get 'transaction/add' => 'pages#form'
  get 'history/invoice/:id' => 'pages#display_invoice'
  post 'transaction/add' => 'pages#create_entry'

  get 'sum' => 'pages#sum'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  has_attached_file :invoice_jpg, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :invoice_jpg, content_type: /\Aimage\/.*\Z/
end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
  has_attached_file :invoice_jpg, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :invoice_jpg, content_type: /^image\/(png|gif|jpeg|jpg)/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @history_tab = false
    if request.xhr?
      render 'index', layout: false
    else
      render 'index'
    end
  end

  def history
    @history_tab = true
    unless params[:begin_date].nil? || params[:end_date].nil?
      @revenues = Revenue.where(date: (params[:begin_date]..params[:end_date]))
      @expenses = Expense.where(date: (params[:begin_date]..params[:end_date]))
    else
      @revenues = Revenue.all
      @expenses = Expense.all
    end
    @records = @revenues + @expenses

    if request.xhr?
      if params[:type] == "#revenue"
        render partial: 'table', layout: false, locals: {records: @revenues}
      elsif params[:type] == "#expense"
        render partial: 'table', layout: false, locals: {records: @expenses}
      elsif params[:type] == "#all"
        render partial: 'table', layout: false, locals: {records: @records}
      elsif params[:type] == "datepicker"
        render partial: 'table', layout: false, locals: {records: @records}
      else
        render 'history', layout: false
      end
    end

  end

  #display invoice in modal
  def display_invoice
    @invoice = Revenue.find(params[:id])
    render partial: 'invoice', layout: false
  end

  # Display form in modal for add entry
  def form
    render partial: 'form', layout: false
  end

  #submit form for add entry
  def create_entry
    @revenue = Revenue.new( revenue_params )
    @revenue.doc_img = "sample_invoice4.png"
    @revenue.save

    redirect_to history_index_path
  end

  # Sums up revenues and expenses up to current date
  def sum
    p Date.today
    p Date.today - params[:timeframe].to_i
    revenues = Revenue.select("date", "SUM(total)").where("date > ?", Date.today - params[:timeframe].to_i).group("date").order("date")
    expenses = Expense.select("date", "SUM(total)").where("date > ?", Date.today - params[:timeframe].to_i).group("date").order("date")
    @data = [revenues, expenses]
    render json: @data
  end

  private
  def revenue_params

    params.require(:revenue).permit(:invoice_jpg, :date, :invoice_number, :vendor, :category, :description, :total, :country, :quantity)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mortar Analytics</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="with-iconav">

    <nav class="iconav">
      <div class="iconav-brand" href="/">
        <span class="icon icon-leaf iconav-brand-icon"></span>
      </div>
      <div class="iconav-slider">
        <ul class="nav nav-pills iconav-nav">
          <% if @history_tab %>
            <li>
          <% else %>
            <li class="active">
          <% end %>
            <a href="/" class="navbar-icons" title="Overview" data-placement="right" data-container="body">
              <span class="icon icon-area-graph"></span>
              <small class="iconav-nav-label visible-xs-block">Overview</small>
            </a>
          </li>
          <% if @history_tab %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
            <a href="/history/index" class="navbar-icons" title="History" data-placement="right" data-container="body">
              <span class="icon icon-text-document"></span>
              <small class="iconav-nav-label visible-xs-block">History</small>
            </a>
          </li>
          <li >
            <a href="/#" class="navbar-icons" title="Fluid layout" id="about-click" data-placement="right" data-container="body">
              <span class="icon icon-globe"></span>
              <small class="iconav-nav-label visible-xs-block">About</small>
            </a>
          </li>
        </ul>
      </div>
    </nav>
      <div id="overlay"></div>
    <div id="about-modal">
      <h2 class="modal-title">About Mortar Analytics</h2>
      <p>Welcome to Mortar Analytics! This is a CRM platform for business owners to easily submit and keep track of their business transactions.</p>
      <p>To use, simply click on the <span class="icon icon-text-document"></span> icon on the left to access the invoice statement. Here you can add invoices, filter through existing invoices, and edit them. If an image of the invoice was attached to an invoice, you can view it by clicking on the invoice number.</p>
      <p>The <span class="icon icon-area-graph"></span> link will take you to a stack chart that will display the revenue/expense trends for a given period. This chart will automatically update with the invoices that have been input in the system.</p>
    </div>

    <div class="container">
    <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for :revenue, url: transaction_add_path, remote: true do |form| %>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <div class="radio-inline">
          <label>
            <input type="radio" name="revenue[type]" id="revenueRadio" value="revenue" checked>Revenue
          </label>
        </div>
        <div class="radio-inline">
          <label>
            <input type="radio" name="type" id="expenseRadio" value="expense">Expense
          </label>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label for="exampleInputEmail1">Date</label>
        <div class="input-with-icon">
          <input type="text" id="formEntryDate" name="revenue[date]" class="form-control" data-provide="datepicker">
          <span class="icon icon-calendar"></span>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Invoice Number</label>
        <input type="text" class="form-control" id="form_invoice_number" name="revenue[invoice_number]" placeholder="10048">
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Category</label>
        <input type="text" class="form-control" name="revenue[category]" id="form_type" placeholder="Consulting Fee/Product Sale/Rental Expense">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Client/Supplier</label>
        <input type="text" class="form-control" name="revenue[vendor]" id="form_vendor_name" placeholder="FedEx/Office Depot">
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Country</label>
        <input type="text" name="revenue[country]" class="form-control" id="form_country" placeholder="(Optional for Expense)">
      </div>
    </div>
  </div>

  <div class="form-group">
    <label for="exampleInputFile">Description</label>
    <textarea class="form-control" name="revenue[description]" rows="3" placeholder="Computer repair fee"></textarea>
  </div>

  <div class="form-group">
    <label for="exampleInputFile">Quantity</label>
    <input type="number" name="revenue[quantity]" min=0 class="form-control" id="form_quantity" placeholder="(Optional for Expense)">
  </div>

  <div class="form-group">
    <label for="exampleInputFile">Total Price</label>
    <input type="number" name="revenue[total]" min=0 class="form-control" id="form_total" placeholder="90500">
  </div>

  <%= form.file_field :invoice_jpg %>

  <button type="submit" class="btn btn-default">Submit</button>


<% end %>

app/views/pages/_invoice.html.erb
<% if @invoice.invoice_jpg_file_name.nil? %>
  <img class="img-responsive" src="/images/<%= @invoice.doc_img %>" >
<% else %>
  <%= image_tag(@invoice.invoice_jpg.url, class: "img-responsive") %>
<% end %>

app/views/pages/_table.html.erb
<table class="table tablesorter" id="historyTable" data-sort="table">
    <thead>
      <tr>

        <th id="type-column">  </th>
        <th id="date-column">Date</th>
        <th id="vendor-column">Client/Supplier</th>
        <th id="quantity-column">Quantity</th>
        <th id="expense-type-column">Category</th>
        <th id="description-column">Description</th>
        <th id="country-column">Country</th>
        <th id="total-column">Total</th>
        <th id="invoice-column">Invoice Number</th>
        <th id="edit-column"></th>
      </tr>
    </thead>
    <tbody>
      <% records.each do |record| %>
      <tr>

        <td><%= record.kindof == 'Expenditure' ? "Expense" : "Revenue" %></td>
        <td><%= record.date %></td>
        <td><%= record.vendor %></td>
        <td><%= record.quantity.nil? ? "None" : record.quantity %></td>
        <td><%= record.category %></td>
        <td><%= record.description %></td>
        <td><%= record.country %></td>
        <td>$<%= record.total.to_i %></td>
        <td><a data-toggle="modal" data-target="#myModal" data-invoice="<%= record.doc_img %>" data-id="<%= record.id%>">A<%= record.invoice_number %></td>
        <td><a href="#">Edit</a></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/pages/history.html.erb
  <div class="dashhead">
   <div class="dashhead-titles">
    <h6 class="dashhead-subtitle">Dashboards</h6>
    <h2 class="dashhead-title">Transaction Details</h2>
   </div>


  <div class="btn-toolbar dashhead-toolbar">
    <div class="btn-toolbar-item input-with-icon">
      <div class="input-group input-daterange date-search">
          <input type="text" class="form-control" id="datepicker-begin" data-provide="datepicker">
          <span class="input-group-addon form-control">to</span>
          <input type="text" class="form-control" id="datepicker-end" data-provide="datepicker">
          <button type="submit" id="submit-datepicker" class="btn btn-default">Update</button>
      </div>
    </div>
  </div>
</div>



<div class="hr-divider">
  <ul class="table-tabs nav nav-pills hr-divider-content hr-divider-nav">
    <li id="all-tab" class="active">
      <a href="#all">All</a>
    </li>
    <li id="revenue-tab">
      <a href="#revenue">Revenue</a>
    </li>
    <li id="expense-tab">
      <a href="#expense">Expense</a>
    </li>
  </ul>
</div>

<div class="flextable table-actions">
  <div class="flextable-item">
    <div class="btn-group">
      <button type="submit" data-toggle="modal" data-target="#addEntryModal" id="add-entry" class="btn btn-primary-outline">
        <span class="icon icon-plus"></span>
      </button>
    </div>
  </div>
</div>

<div class="table-full">
  <div class="table-responsive" id="history-table-container">
    <%= render partial: 'table', layout: false, locals: {records: @records} %>
  </div>
</div>

<div class="text-center">
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-invoice="sample_invoice.jpg" data-target="#myModal">
  Test
</button>

<!-- Invoice Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Invoice</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Form Modal -->
<div class="modal fade" id="addEntryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Entry</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
  <div class="dashhead">
    <div class="dashhead-titles">
      <h6 class="dashhead-subtitle">Dashboards</h6>
      <h2 class="dashhead-title">Overview</h2>
    </div>

    <div class="btn-toolbar dashhead-toolbar">
      <div class="btn-toolbar-item input-with-icon">
        <input type="text" value="01/01/15 - 01/08/15" class="form-control" data-provide="datepicker">
        <span class="icon icon-calendar"></span>
      </div>
    </div>
  </div>

  <hr class="m-t">

  <div id="stacked-chart-container">
    <h2 class="pull-left">Profits Vs. Expenses</h2>
    <div class="btn-group dashhead-toolbar-item btn-group-thirds pull-right">
      <button type="button" class="btn btn-primary-outline active" id="stacked-7">Week</button>
      <button type="button" class="btn btn-primary-outline" id="stacked-14">2 Weeks</button>
      <button type="button" class="btn btn-primary-outline" id="stacked-30">Month</button>
    </div>
    <div id="chart" style="width:100%">
      <svg id="chart" style="height:500px">
    </div>
  </div>

  <div class="hr-divider m-t-md m-b">
    <h3 class="hr-divider-content hr-divider-heading">Summary</h3>
  </div>

  <div class="row text-center m-t-lg">
    <div class="col-sm-4 m-b-md">
      <div class="w-lg m-x-auto">
        <div id="pie-chart-7">
          <svg class="pie-chart" style="height:300px">
        </div>
      </div>
      <strong class="text-muted">1-Week</strong>
    </div>
    <div class="col-sm-4 m-b-md">
      <div class="w-lg m-x-auto">
        <div id="pie-chart-14">
          <svg class="pie-chart" style="height:300px">
        </div>
      </div>
      <strong class="text-muted">2-Week</strong>
    </div>
    <div class="col-sm-4 m-b-md">
      <div class="w-lg m-x-auto">
        <div id="pie-chart-30">
          <svg class="pie-chart" style="height:300px">
        </div>
      </div>
      <strong class="text-muted">1-Month</strong>
    </div>
  </div>

<hr class="m-t">